import { defineStore } from 'pinia'
import { ref } from 'vue'

export const useMusicStore = defineStore('music', () => {
  // 响应式状态
  const musicList = ref([
    {
      id: 1,
      title: 'Frozen World',
      artist: 'KurykuleP',
      mapper: 'kerartt',
      difficulty: 'Normal',
      bpm: 160,
      stars: 5.2,
      playCount: 671,
      duration: '05:34',
    },
    {
      id: 2,
      title: 'Gardens',
      artist: 'Unknown Artist',
      mapper: 'mapper1',
      difficulty: 'Normal',
      bpm: 128,
      stars: 3.8,
      playCount: 482,
      duration: '03:22',
    },
    {
      id: 3,
      title: 'BLACK-RAY',
      artist: 'Camellia',
      mapper: 'peppy',
      difficulty: 'Hard',
      bpm: 175,
      stars: 6.2,
      playCount: 1209,
      duration: '03:45',
    },
    {
      id: 4,
      title: 'The Arrogance of Agony',
      artist: 'Mental Cruelty',
      mapper: 'RLC',
      difficulty: 'Insane',
      bpm: 195,
      stars: 7.3,
      playCount: 843,
      duration: '03:56',
    },
    {
      id: 5,
      title: 'Touhiron',
      artist: 'Camellia feat. Nanahira',
      mapper: 'Sotarks',
      difficulty: 'Hard',
      bpm: 182,
      stars: 5.9,
      playCount: 1520,
      duration: '03:27',
    },
    {
      id: 6,
      title: 'FAKE PROMISE',
      artist: 'DJ SHARPNEL',
      mapper: 'mapper3',
      difficulty: 'Insane',
      bpm: 200,
      stars: 6.8,
      playCount: 521,
      duration: '04:12',
    },
    {
      id: 7,
      title: 'artefatta vita',
      artist: "witch's slave",
      mapper: 'mapper4',
      difficulty: 'Easy',
      bpm: 120,
      stars: 2.4,
      playCount: 256,
      duration: '02:48',
    },
    {
      id: 8,
      title: 'artefatta vita',
      artist: "witch's slave",
      mapper: 'mapper4',
      difficulty: 'Easy',
      bpm: 120,
      stars: 2.4,
      playCount: 256,
      duration: '02:48',
    },
    {
      id: 9,
      title: 'artefatta vita',
      artist: "witch's slave",
      mapper: 'mapper4',
      difficulty: 'Easy',
      bpm: 120,
      stars: 2.4,
      playCount: 256,
      duration: '02:48',
    },
    {
      id: 10,
      title: 'artefatta vita',
      artist: "witch's slave",
      mapper: 'mapper4',
      difficulty: 'Easy',
      bpm: 120,
      stars: 2.4,
      playCount: 256,
      duration: '02:48',
    },
    {
      id: 11,
      title: 'artefatta vita',
      artist: "witch's slave",
      mapper: 'mapper4',
      difficulty: 'Easy',
      bpm: 120,
      stars: 2.4,
      playCount: 256,
      duration: '02:48',
    },
    {
      id: 12,
      title: 'artefatta vita',
      artist: "witch's slave",
      mapper: 'mapper4',
      difficulty: 'Easy',
      bpm: 120,
      stars: 2.4,
      playCount: 256,
      duration: '02:48',
    },
  ]);

  return {
    musicList,
  };
});

